# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            "Gerson's page"
tagline:          'A place for (almost) everything'
description:      'Here I try to place some thoughts, some works, some... thing'
url:              http://gerson23.github.io
baseurl:          '/'
paginate:         5

author:
  name:           'Gerson Carlos'

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/gerson23/gerson23.github.io
